version: "3.8"

services:
  frontend-app:
    container_name: frontend-app
    build:
      context: .devcontainer
    tty: true
    volumes:
      - .:/app:cached
      - frontend_node_modules:/app/node_modules
    ports:
      - 3000:3000
      - 24600:24600

volumes:
  frontend_node_modules:
